"use strict";
let number1 = 7;
console.log("Is number == 7? I predict True.");
console.log(number1 === 7);
let name4 = "Alice";
console.log("Is name == 'Alice'? I predict True.");
console.log(name4 === 'Alice');
let isSunny = true;
console.log("Is it sunny outside? I predict True.");
console.log(isSunny);
let age = 25;
console.log("Is age < 30? I predict True.");
console.log(age < 30);
let isAdmin = false;
console.log("Is user an admin? I predict False.");
console.log(isAdmin);
let temperature = 20;
console.log("Is temperature >= 30? I predict False.");
console.log(temperature >= 30);
let fruit = "apple";
console.log("Is fruit == 'banana'? I predict False.");
console.log(fruit === 'banana');
let isWeekend = true;
console.log("Is it the weekend? I predict True.");
console.log(isWeekend);
let score = 85;
console.log("Is score > 90? I predict False.");
console.log(score > 90);
let isRaining = false;
console.log("Is it raining? I predict False.");
console.log(isRaining);
